
const getters = {
  fsUserAgent: state => state.artificial.fsUserAgent,
  artificialStatus: state => state.artificial.artificialStatus,
  fsStatus: state => { // 人工坐席呼叫状态
    const { fsUserAgent } = state.artificial
    if (fsUserAgent) {
      return fsUserAgent.state
    } else {
      return ''
    }
  },
  artiModalVisible: state => state.artificial.artiModalVisible,
  artiCustomerData: state => state.artificial.artiCustomerData,
  artiInfo: state => state.artificial.artiInfo,
  dialInfo: state => state.artificial.dialInfo,
  assistantDialogFlowId: state => state.artificial.assistantDialogFlowId,
  historyVisible: state => state.artificial.historyVisible,
  newCallRecordId: state => state.artificial.newCallRecordId,
  hangupBy: state => state.artificial.hangupBy,
  useAiAssistant: state => state.artificial.useAiAssistant,
  callType: state => state.artificial.callType,
  artiJoinList: state => state.artificial.artiJoinList,
  artiJoinModalData: state => state.artificial.artiJoinModalData,
  artiJoinModalVisible: state => state.artificial.artiJoinModalVisible,
  artiJoinModalType: state => state.artificial.artiJoinModalType,
  knowledgeModalVisible: state => state.artificial.knowledgeModalVisible,
  batchJobStatus: state => state.artificial.batchJobStatus,
  batchJobVisible: state => state.artificial.batchJobVisible,
  isRongLian: state => state.app.isRongLian,
  NoLogoNorWx: state => state.app.NoLogoNorWx,
  isYuHangJianKongJu: state => state.app.isYuHangJianKongJu,
  isGongDaoBeiJingIP: state => state.app.isGongDaoBeiJingIP,
  isGongdao: state => state.app.isGongdao,
  needBusinessAnalysis: state => state.app.needBusinessAnalysis,
  customerStr: state => state.app.customerStr,
  sidebar: state => state.app.sidebar,
  clientHeight: state => state.app.clientHeight,
  language: state => state.app.language,
  device: state => state.app.device,
  showResetPswTip: state => state.app.showResetPswTip,
  hasEnvironmentTest: state => state.app.hasEnvironmentTest,
  auth_warnMsg_view: state => state.app.auth_warnMsg_view,
  auth_sysMsg_view: state => state.app.auth_sysMsg_view,
  crm_early_warning_view: state => state.app.crm_early_warning_view,
  distributorLevel: state => state.user.distributorLevel,
  avatar: state => state.user.avatar,
  userId: state => state.user.userId,
  name: state => state.user.name,
  companyName: state => state.user.companyName,
  description: state => state.user.description,
  status: state => state.user.status,
  access: state => state.user.access,
  gender: state => state.user.gender,
  setting: state => state.user.setting,
  createTime: state => state.user.createTime,
  position: state => state.user.position,
  phoneNumber: state => state.user.phoneNumber,
  wechat: state => state.user.wechat,
  downloadingAudio: state => state.app.downloadingAudio,
  downloadingCur: state => state.app.downloadingCur,
  downloadingTotal: state => state.app.downloadingTotal,
  modalVisibleSwitch: state => state.app.modalVisibleSwitch,
  curEditGroupId: state => state.tag.curEditGroupId,
  wxHeadimgurl: state => state.user.wxHeadimgurl,
  wxOfficialAccountBinded: state => state.user.wxOfficialAccountBinded,
  username: state => state.user.username,
  role: state => state.user.role,
  organization: state => state.user.organization,
  manager: state => state.user.manager,
  csAuth: state => state.user.csAuth,
  dialIntervalStart: state => state.user.dialIntervalStart,
  dialIntervalEnd: state => state.user.dialIntervalEnd,
  enableLineStatsView: state => state.user.enableLineStatsView,
  enableCsSeat: state => state.user.csAuth.enableCsSeat, // 是否开通人工坐席
  tenantSign: state => state.user.tenantSign,
  tenantId: state => state.user.tenantId,
  callbackUrl: state => state.user.callbackUrl,
  smsCallbackUrl: state => state.user.smsCallbackUrl,
  openISV: state => state.user.openISV,
  iconUrl: state => state.user.iconUrl,
  userEnableCsSeat: state => state.user.csAuth.userEnableCsSeat, // 是否存在启用状态的人工坐席，在坐席管理-》人工坐席页面查看
  enableAiAssistant: state => state.user.csAuth.enableAiAssistant,
  enableCsTransfer: state => state.user.csAuth.enableCsSeat, // enableCsTransfer,
  enableCsTransferTel: state => state.user.csAuth.enableCsTransferTel,
  enableCallIn: state => state.user.csAuth.enableCallIn,
  enableIvr: state => state.user.csAuth.enableIvr,
  enableVoiceQualityControl: state => state.user.csAuth.enableVoiceQualityControl,
  enableTaskWaitingTimeout: state => state.user.csAuth.enableTaskWaitingTimeout,
  aiConcurrencyLevel: state => state.user.aiConcurrencyLevel, // 有效ai数量
  aiExpiredLevel: state => state.user.aiExpiredLevel, // 过期ai数量
  accountFare: state => state.user.accountFare, // 账户余额
  expireTime: state => state.user.expireTime, // 账号过期时间
  customerCountLimit: state => state.user.customerCountLimit, // 用户可拥有客户数量
  customerDaysLimit: state => state.user.customerDaysLimit, // 用户拥有客户剩余的天数
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  personalizedData: state => state.permission.personalizedData,
  flowData: state => state.talk.flowData,
  flowList: state => state.talk.flowData ? state.talk.flowData.content : [],
  flowItem: state => state.talk.flowItem || {},
  flowId: state => state.talk.flowItem.id,
  stepId: state => state.talk.stepId,
  intentBranchList: state => state.talk.intentBranchList,
  industryList: state => state.talk.industryList,
  appType: state => state.talk.appType,
  hasBranchUpdateAccess: state => state.talk.hasBranchUpdateAccess,
  hasEditAccess: state => state.talk.hasEditAccess,
  hasDeleteAccess: state => state.talk.hasDeleteAccess,
  nodeDataArray: state => state.talk.nodeDataArray,
  linkDataArray: state => state.talk.linkDataArray,
  totalNodeCount: state => state.talk.totalNodeCount,
  recordNodeCount: state => state.talk.recordNodeCount,
  isModified: state => state.talk.isModified,
  isLocal: state => state.talk.isLocal,
  jumpToHumanServiceCount: state => state.talk.jumpToHumanServiceCount,
  humanInterventionCount: state => state.talk.humanInterventionCount,
  redialTimeExist: state => state.talk.redialTimeExist,
  voiceType: state => state.talk.voiceType,
  auth_addOrEditOrCopy: state => state.talk.auth_addOrEditOrCopy, // 新建/编辑/复制话术
  auth_delOrExport: state => state.talk.auth_delOrExport, // 删除/导出话术
  auth_DefaultBranch_view: state => state.talk.auth_DefaultBranch_view, // 查看默认分支
  auth_DefaultBranch_edit: state => state.talk.auth_DefaultBranch_edit, // 编辑默认分支
  auth_uploadAudio: state => state.talk.auth_uploadAudio, // 录音上传
  robotCallJobId: state => state.task.robotCallJobId,
  robotCallJobStatus: status => status.task.robotCallJobStatus,
  humanIntervention: state => state.taskV2.humanIntervention, // 人工介入
  humanService: state => state.taskV2.humanService, // 转人工
  isPlaying: state => state.callDetail.isPlaying,
  showDownloadAndUploadDot: state => state.navbarDot.showDownloadAndUploadDot,
  showWarnningMessageDot: state => state.navbarDot.showWarnningMessageDot,
  showSystemAnnouncementDot: state => state.navbarDot.showSystemAnnouncementDot,
  intervalTagList: state => state.intervalTag.intervalTagList,
  curIntervalTagName: state => state.intervalTag.curIntervalTagName,
  innerTagList: state => state.intervalTag.innerTagList,
  auth_intentionTag_view: state => state.intervalTag.auth_intentionTag_view, // 查看意向标签页面
  auth_intentionTag_addOrEdit: state => state.intervalTag.auth_intentionTag_addOrEdit, // 新建/编辑/复制/删除标签分组
  selectedDeviceId: state => state.gateway.selectedDeviceId,
  customerFields_private: state => state.customerFields.customerFields_private,
  customerFields_public: state => state.customerFields.customerFields_public,
  customerFields_all: state => state.customerFields.customerFields_all,
  customerFields_contactHistory: state => state.customerFields.customerFields_contactHistory,
  customerFieldsList: state => state.customerFields.customerFieldsList,
  private_checked_fields: state => state.customerFields.private_checked_fields, // 我的客户 当前选中展示字段
  private_all_fields: state => state.customerFields.private_all_fields, // 我的客户 所有表格字段
  public_checked_fields: state => state.customerFields.public_checked_fields, // 客户公海 当前选中展示字段
  public_all_fields: state => state.customerFields.public_all_fields, // 客户公海 所有表格字段
  call_checked_fields: state => state.customerFields.call_checked_fields, // 联系历史 当前选中展示字段
  call_all_fields: state => state.customerFields.call_all_fields, // 联系历史 所有表格字段
  allcus_checked_fields: state => state.customerFields.allcus_checked_fields, // 所有客户 当前选中展示字段
  allcus_all_fields: state => state.customerFields.allcus_all_fields // 所有客户 所有表格字段
}
export default getters
